### ISSUE TITLE
Package `lezer-feel` should be updated so that users of the `bpmn-js` ecosystem don't get duplicate packages

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/feelers#19]
### Describe the Bug

See [this](https://github.com/bpmn-io/bpmn-js/issues/1869) for a discussion. The gist is - `feelers` depends on an old version of `lezer-feel` and people who use `camunda-bpmn-js` get it multiple times because of other dependencies which depend on a later version of it.

The same is true for the `@bpmn-io/feel-lint` package by the way.

### Steps to Reproduce

1. Install `camunda-bpmn-js`.
2. Check `package-lock.json` to see duplicate versions of `lezer-feel` and `@bpmn-io/feel-lint`.

### Expected Behavior

No duplicates.

### Environment

- Host (Browser/Node version), if applicable: N/A
- OS: Linux
- Library version: 0.1.0

**Comment by boris-petrov** [comment]
@nikku thanks for fixing that! Please don't forget to also update `@bpmn-io/feel-lint` which also would be duplicated otherwise.

**Comment by nikku** [comment]
Done via `feelers@1.1.0`. Thanks.
