### ISSUE TITLE
"export 'FeelersEditor' was not found in 'feelers'

### ISSUE THREAD

**Issue by EricGDW** [bpmn-io/feelers#22]
### Steps to Reproduce

1. do this
2. do that
3. now this happens

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Thanks for your report. If you provide additional details then we may be able to help you.
